server:
  port: 8080

spring:
  # 只配置了账号、密码、数据库地址、连接驱动，因为默认使用的是 class com.zaxxer.hikari.HikariDataSource 数据源
  datasource:
    # mysql连接
    username: root
    password: 123456abAB&
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接池
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select ‘x‘
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    password: Redis!12345
    port: 6379
    host: 192.168.0.107
    timeout: 3000
    database: 0

  #showSql
  logging:
    level:
      org:
        pp:
          mapper: debug

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: org.pp.springboot_mybatis.entity

# springboot2 可视化管理 http://localhost:9001/actuator
management:
  #actuator端口
  server:
    port: 9001
  #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
  endpoints:
    web:
      base-path: /actuator
      #开放所有页面节点  默认只开启了health、info两个节点
      exposure:
        include: "*"
    #显示健康具体信息  默认不会显示详细信息
  endpoint:
    health:
      show-details: always